version: '3'
services:
  dev-service:
      # Note that the path of the Dockerfile and context is relative to the *primary*
      # docker-compose.yml file (the first in the devcontainer.json "dockerComposeFile"
      # array). The sample below assumes your primary file is in the root of your project.
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
      args:
        VARIANT: "ubuntu-22.04"
    volumes:
      - .:/workspace
      - bashhistory:/commandhistory
    command: /bin/sh -c "while sleep 1000; do :; done"
    networks:
      - internal
  #redis:
  #  image: redis:6.2-alpine
  #  restart: always
  #  environment:
  #    - ALLOW_EMPTY_PASSWORD=yes
  #  ports:
  #    - '6379:6379'
  #  networks:
  #    - internal
  #  command: redis-server --loglevel warning
  #  volumes:
  #    - redis:/data
  #kafka:
  #  image: bitnami/kafka:latest
  #  container_name: kafka
  #  ports:
  #    - 9092:9092
  #    - 9093:9093
  #  environment:
  #    - KAFKA_CFG_NODE_ID=1
  #    - KAFKA_CFG_PROCESS_ROLES=broker,controller
  #    - KAFKA_CFG_LISTENERS=CONTROLLER://:9094,INTERNAL://:9093,OUTSIDE://:9092
  #    - KAFKA_CFG_ADVERTISED_LISTENERS=INTERNAL://kafka:9093,OUTSIDE://localhost:9092
  #    - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,INTERNAL:PLAINTEXT,OUTSIDE:PLAINTEXT
  #    - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
  #    - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=INTERNAL
  #    - KAFKA_KRAFT_CLUSTER_ID=some-random-cluster-id
  #    - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka:9094
  #  networks:
  #    - internal
  #kafka-ui:
  #  container_name: kafka-ui
  #  image: provectuslabs/kafka-ui:latest
  #  ports:
  #    - 8080:8080
  #  environment:
  #    DYNAMIC_CONFIG_ENABLED: 'true'
  #  networks:
  #    - internal


networks:
  internal:

volumes:
    bashhistory:
    kafka:
    redis:
