version: '3'
services:
  dev-service:
      # context and volumes are relative to this compose file.
      # dockerfile is relative to the build context (the repo root).
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
      args:
        VARIANT: "ubuntu-22.04"
    volumes:
      - ..:/workspace/conductor_celery
      - bashhistory:/commandhistory
    working_dir: /workspace/conductor_celery
    command: /bin/sh -c "while sleep 1000; do :; done"
    networks:
      - internal


networks:
  internal:

volumes:
    bashhistory:
